// src/App.svelte
<script lang="ts">
  import Sidebar from './components/Sidebar.svelte';
  import Whiteboard from './components/Whiteboard.svelte';
    import RadialMenu from './components/RadialMenu.svelte';
  import GlobalSettings from './components/GlobalSettings.svelte';
  import type { ExerciseBlockState } from './lib/types';
  import { Difficulty, Tone, ExerciseType } from './lib/types';
  import { initActivityLogger, getActivityLogger } from './services/ActivityLogger';
  import { EXERCISE_SIZE_OVERRIDES, DEFAULT_BLOCK_DIMENSIONS } from './lib/constants';

  $effect(() => {
    initActivityLogger('practice-genie', 'student_default');
    getActivityLogger()?.startSession();
  });

  let isSidebarOpen = $state(true);


  // Local Storage Keys
  const BLOCKS_KEY = 'practiceGenie-blocks';
  const DIFFICULTY_KEY = 'practiceGenie-difficulty';
  const TONE_KEY = 'practiceGenie-tone';
  const THEME_KEY = 'practiceGenie-theme';
  const PATHS_KEY = 'practiceGenie-paths';

  let initialBlocks = [];
  try {
      const savedBlocks = localStorage.getItem(BLOCKS_KEY);
      if (savedBlocks) {
          initialBlocks = JSON.parse(savedBlocks);
      }
  } catch (e) {
      console.error('Failed to parse blocks from localStorage', e);
      localStorage.removeItem(BLOCKS_KEY);
  }
  let blocks = $state<ExerciseBlockState[]>(initialBlocks);

  let initialPaths = [];
  try {
      const savedPaths = localStorage.getItem(PATHS_KEY);
      if (savedPaths) {
          initialPaths = JSON.parse(savedPaths);
      }
  } catch (e) {
      console.error('Failed to parse paths from localStorage', e);
      localStorage.removeItem(PATHS_KEY);
  }
  let paths = $state<any[]>(initialPaths);
  let isDrawingMode = $state(false);

  // Global Settings State
  let isGlobalSettingsOpen = $state(false);
  let globalDifficulty = $state<Difficulty>((localStorage.getItem(DIFFICULTY_KEY) as Difficulty) || Difficulty.B1);
  let globalTone = $state<Tone>((localStorage.getItem(TONE_KEY) as Tone) || Tone.Casual);
  let globalTheme = $state<string>(localStorage.getItem(THEME_KEY) || '');

  $effect(() => { localStorage.setItem(BLOCKS_KEY, JSON.stringify(blocks)); });
  $effect(() => { localStorage.setItem(DIFFICULTY_KEY, globalDifficulty); });
  $effect(() => { localStorage.setItem(TONE_KEY, globalTone); });
  $effect(() => { localStorage.setItem(THEME_KEY, globalTheme); });
  $effect(() => { localStorage.setItem(PATHS_KEY, JSON.stringify(paths)); });

  let globalMakerTemperature = $state<number>(parseFloat(localStorage.getItem('deepseek_maker_temp') || '0.7'));
  let globalCheckerTemperature = $state<number>(parseFloat(localStorage.getItem('deepseek_checker_temp') || '0.2'));


  // Focus Settings State
  let globalFocusVocabulary = $state<string[]>(JSON.parse(localStorage.getItem('practiceGenie-focusVocabulary') || '[]'));
  let globalInclusionRate = $state<number>(parseFloat(localStorage.getItem('practiceGenie-inclusionRate') || '50'));
  let globalFocusGrammar = $state<string[]>(JSON.parse(localStorage.getItem('practiceGenie-focusGrammar') || '[]'));
  let globalGrammarInclusionRate = $state<number>(parseFloat(localStorage.getItem('practiceGenie-grammarInclusionRate') || '50'));

  // App State

  let presentingBlockId = $state<number | null>(null);

  let nextId = $derived(blocks.length > 0 ? Math.max(...blocks.map(b => b.id)) + 1 : 1);
  let maxZIndex = $derived(blocks.length > 0 ? Math.max(...blocks.map(b => b.zIndex)) : 10);


  const handleExportState = () => {
      const data = {
          version: '2.1.0',
          timestamp: new Date().toISOString(),
          state: {
              blocks,
              difficulty: globalDifficulty,
              tone: globalTone,
              theme: globalTheme,
              focusVocabulary: globalFocusVocabulary,
              inclusionRate: globalInclusionRate,
              focusGrammar: globalFocusGrammar,
              grammarInclusionRate: globalGrammarInclusionRate
          }
      };
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `practice-genie-project-${new Date().toISOString().split('T')[0]}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
  };

  const handleImportState = (e: Event) => {
      const target = e.target as HTMLInputElement;
      const file = target.files?.[0];
      if (!file) return;

      const reader = new FileReader();
      reader.onload = (event) => {
          try {
              const result = event.target?.result as string;
              const data = JSON.parse(result);
              if (data && data.state) {
                  const state = data.state;
                  if (state.blocks) blocks = state.blocks;
                  if (state.difficulty) globalDifficulty = state.difficulty;
                  if (state.tone) globalTone = state.tone;
                  if (state.theme) globalTheme = state.theme;
                  if (state.focusVocabulary) globalFocusVocabulary = state.focusVocabulary;
                  if (state.inclusionRate) globalInclusionRate = state.inclusionRate;
                  if (state.focusGrammar) globalFocusGrammar = state.focusGrammar;
                  if (state.grammarInclusionRate) globalGrammarInclusionRate = state.grammarInclusionRate;
                  alert("Project imported successfully!");
              } else {
                  throw new Error("Invalid project file format");
              }
          } catch (error) {
              console.error("Failed to parse project file", error);
              alert("Invalid project file.");
          }
      };
      reader.readAsText(file);
      target.value = '';
  };

  const handleClearBoard = () => {
      if (window.confirm("Are you sure you want to clear the entire whiteboard? This cannot be undone unless you have exported your project.")) {
          blocks = [];
      }
  };


  // Handlers
  const handleAddBlock = (typeStr: string, dropX?: number, dropY?: number) => {
      const type = typeStr as ExerciseType;
      let finalX = 0;
      let finalY = 0;

      const dims = EXERCISE_SIZE_OVERRIDES[type] || DEFAULT_BLOCK_DIMENSIONS;
      const width = dims.width;
      const height = dims.height;

      if (dropX !== undefined && dropY !== undefined) {
          finalX = Math.round(dropX - width/2);
          finalY = Math.round(dropY - height/2);
      } else {
          // Find free position logic equivalent to React version
          // the legacy app used standard screen bounds, here the whiteboard origin is at -5000, -5000
          // Let's place it near the center of the current view by default, or just at a fixed offset
          // To be simple and match the "fallback" logic, let's put it around 0,0 relative to whiteboard center
          finalX = 5000 + 100;
          finalY = 5000 + 100;

          // We want it to be near the center of the screen
          const centerX = 5000 + (window.innerWidth / 2) - (width / 2);
          const centerY = 5000 + (window.innerHeight / 2) - (height / 2);

          let positionFound = false;
          for (let offset = 0; offset < 3000 && !positionFound; offset += 50) {
              for (let angle = 0; angle < Math.PI * 2 && !positionFound; angle += Math.PI / 4) {
                  const checkX = Math.round(centerX + Math.cos(angle) * offset);
                  const checkY = Math.round(centerY + Math.sin(angle) * offset);
                  let hasOverlap = false;
                  for (const block of blocks) {
                      if (
                          checkX < block.x + block.width &&
                          checkX + width > block.x &&
                          checkY < block.y + block.height &&
                          checkY + height > block.y
                      ) {
                          hasOverlap = true;
                          break;
                      }
                  }
                  if (!hasOverlap) {
                      finalX = checkX;
                      finalY = checkY;
                      positionFound = true;
                  }
              }
          }
      }

      const newBlock: ExerciseBlockState = {
          id: nextId,
          exerciseType: type,
          x: finalX,
          y: finalY,
          width,
          height,
          zIndex: maxZIndex + 1,
          difficulty: globalDifficulty,
          tone: globalTone,
          theme: globalTheme || 'General English',
          focusVocabulary: [...globalFocusVocabulary],
          inclusionRate: globalInclusionRate,
          focusGrammar: [...globalFocusGrammar],
          grammarInclusionRate: globalGrammarInclusionRate,
          isGenerated: false
      };
      blocks = [...blocks, newBlock];
  };

  const handleUpdateBlock = (id: number, updates: Partial<ExerciseBlockState>) => {
      blocks = blocks.map(b => b.id === id ? { ...b, ...updates } : b);
  };

  const handleRemoveBlock = (id: number) => {
      blocks = blocks.filter(b => b.id !== id);
      if (presentingBlockId === id) presentingBlockId = null;
  };

  const handleFocusBlock = (id: number) => {
      blocks = blocks.map(b => b.id === id ? { ...b, zIndex: maxZIndex + 1 } : b);
  };

  const cycleDifficulty = () => {
      const diffs = Object.values(Difficulty);
      const idx = diffs.indexOf(globalDifficulty);
      globalDifficulty = diffs[(idx + 1) % diffs.length];
  };
</script>

<div class="h-screen w-screen flex font-sans antialiased overflow-hidden bg-shell">

  <RadialMenu
      difficulty={globalDifficulty}
      onToggleSettings={() => isGlobalSettingsOpen = true}
      onToggleSidebar={() => isSidebarOpen = !isSidebarOpen}
      onExportState={handleExportState}
      onCycleDifficulty={cycleDifficulty}
      isDrawingMode={isDrawingMode}
      onToggleDrawingMode={() => isDrawingMode = !isDrawingMode}
  />


  <Sidebar
    {isSidebarOpen}
    onAddExercise={handleAddBlock}
    focusVocabulary={globalFocusVocabulary}
    onUpdateFocusVocabulary={(v: string[]) => { globalFocusVocabulary = v; localStorage.setItem('practiceGenie-focusVocabulary', JSON.stringify(v)); }}
    inclusionRate={globalInclusionRate}
    onUpdateInclusionRate={(r: number) => { globalInclusionRate = r; localStorage.setItem('practiceGenie-inclusionRate', r.toString()); }}
    focusGrammar={globalFocusGrammar}
    onUpdateFocusGrammar={(g: string[]) => { globalFocusGrammar = g; localStorage.setItem('practiceGenie-focusGrammar', JSON.stringify(g)); }}
    grammarInclusionRate={globalGrammarInclusionRate}
    onUpdateGrammarInclusionRate={(r: number) => { globalGrammarInclusionRate = r; localStorage.setItem('practiceGenie-grammarInclusionRate', r.toString()); }}
    onExportState={handleExportState}
    onImportState={handleImportState}
    onClearBoard={handleClearBoard}
  />


  {#if isGlobalSettingsOpen}
      <GlobalSettings
        onClose={() => isGlobalSettingsOpen = false}
        difficulty={globalDifficulty}
        setDifficulty={(d) => globalDifficulty = d}
        tone={globalTone}
        setTone={(t) => globalTone = t}
        theme={globalTheme}
        setTheme={(t) => globalTheme = t}
        totalTime={blocks.reduce((acc, b) => acc + (b.quantity || 1), 0)}
        makerTemperature={globalMakerTemperature}
        setMakerTemperature={(t) => {
            globalMakerTemperature = t;
            localStorage.setItem('deepseek_maker_temp', t.toString());

        }}
        checkerTemperature={globalCheckerTemperature}
        setCheckerTemperature={(t) => {
            globalCheckerTemperature = t;
            localStorage.setItem('deepseek_checker_temp', t.toString());

        }}
      />
  {/if}

  <!-- Overlay for mobile - Smooth transition -->
  <div
      class="fixed inset-0 bg-black/60 backdrop-blur-sm z-30 lg:hidden transition-opacity duration-300 ease-in-out {isSidebarOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'}"
      aria-hidden="true"
      onclick={() => isSidebarOpen = false}
  ></div>

  <div class="flex-grow flex flex-col relative canvas-grid">
    <Whiteboard
      {blocks}
      {paths}
      {isDrawingMode}
      onPathsChange={(newPaths) => paths = newPaths}
      onAddBlock={handleAddBlock}
      onUpdateBlock={handleUpdateBlock}
      onRemoveBlock={handleRemoveBlock}
      onFocusBlock={handleFocusBlock}
      {presentingBlockId}
      onEnterPresentation={(id) => presentingBlockId = id}
      onExitPresentation={() => presentingBlockId = null}
      onNextSlide={() => {}}
      onPrevSlide={() => {}}
    />
  </div>
</div>

// App.tsx
import React, { useState, useCallback, useEffect, useMemo, useRef } from 'react';
import Sidebar from './components/Sidebar';
import Whiteboard from './components/Whiteboard';
import RadialMenu from './components/RadialMenu';
import GlobalSettings from './components/GlobalSettings';
import { ExerciseType, Difficulty, Tone } from './enums';
import { DrawingPath, ExerciseBlockState } from "./types";
import { EXERCISE_SIZE_OVERRIDES, DEFAULT_BLOCK_DIMENSIONS, calculateExerciseDuration, DIFFICULTY_LEVELS } from './constants';


import { useDebouncedSave } from './hooks/useDebouncedSave';
import { findFreePosition } from './placementUtils';
import { useStudentId, useActivityLogger } from './ActivityContext';

const APP_PREFIX = 'practiceGenie-';

const getStorageKey = (baseKey: string, studentId: string | null): string => {
  return studentId ? `${APP_PREFIX}${studentId}-${baseKey}` : `${APP_PREFIX}${baseKey}`;
};

const useStudentStorageKeys = (studentId: string | null) => {
  return useMemo(() => ({
    BLOCKS_KEY: getStorageKey('blocks', studentId),
    PATHS_KEY: getStorageKey('paths', studentId),
    PAGES_KEY: getStorageKey('pages', studentId),
    DIFFICULTY_KEY: getStorageKey('difficulty', studentId),
    TONE_KEY: getStorageKey('tone', studentId),
    THEME_KEY: getStorageKey('theme', studentId),
    VOCAB_KEY: getStorageKey('focusVocabulary', studentId),
    INCLUSION_RATE_KEY: getStorageKey('inclusionRate', studentId),
    GRAMMAR_KEY: getStorageKey('focusGrammar', studentId),
    GRAMMAR_RATE_KEY: getStorageKey('grammarInclusionRate', studentId),
  }), [studentId]);
};

const App: React.FC = () => {
  const studentId = useStudentId();
  const { logFocusItem, logger } = useActivityLogger();
  const storageKeys = useStudentStorageKeys(studentId);
  const initializationErrors = useRef<{key: string, error: string}[]>([]);

  const [blocks, setBlocks] = useState<ExerciseBlockState[]>(() => {
    let currentKey = storageKeys.PAGES_KEY;
    try {
      const savedPages = localStorage.getItem(storageKeys.PAGES_KEY);
      if (savedPages) {
          const parsedPages = JSON.parse(savedPages);
          if (Array.isArray(parsedPages) && parsedPages.length > 0 && 'blocks' in parsedPages[0]) {
              const migratedBlocks = parsedPages.flatMap((page: any) => 
                page.blocks.map((b: any) => ({...b, isGenerated: false}))
              );
              localStorage.removeItem(storageKeys.PAGES_KEY);
              return migratedBlocks;
          }
      }

      currentKey = storageKeys.BLOCKS_KEY;
      const savedBlocks = localStorage.getItem(storageKeys.BLOCKS_KEY);
      const parsedBlocks = savedBlocks ? JSON.parse(savedBlocks) : [];
      if (Array.isArray(parsedBlocks)) {
          return parsedBlocks.map((b: any) => ({ ...b, isGenerated: false }));
      }
      return [];
    } catch (err: any) {
      const msg = err?.message || 'Unknown error';
      console.error(`[App] LocalStorage initialization error for key "${currentKey}":`, msg);
      initializationErrors.current.push({ key: currentKey, error: msg });
      return [];
    }
  });

  const [paths, setPaths] = useState<DrawingPath[]>(() => {
    try {
      const saved = localStorage.getItem(storageKeys.PATHS_KEY);
      return saved ? JSON.parse(saved) : [];
    } catch (err: any) {
      const msg = err?.message || 'Unknown error';
      console.error(`[App] LocalStorage initialization error for key "${storageKeys.PATHS_KEY}":`, msg);
      initializationErrors.current.push({ key: storageKeys.PATHS_KEY, error: msg });
      return [];
    }
  });

  const [isDrawingMode, setIsDrawingMode] = useState(false);

  const [difficulty, setDifficulty] = useState<Difficulty>(() => {
      const saved = localStorage.getItem(storageKeys.DIFFICULTY_KEY);
      if (saved && Object.values(Difficulty).includes(saved as Difficulty)) {
          return saved as Difficulty;
      }
      return Difficulty.B1;
  });
  const [tone, setTone] = useState<Tone>(() => (localStorage.getItem(storageKeys.TONE_KEY) as Tone) || Tone.Casual);
  const [theme, setTheme] = useState<string>(() => localStorage.getItem(storageKeys.THEME_KEY) || 'Daily Conversations');
  
  const [focusVocabulary, setFocusVocabulary] = useState<string[]>(() => {
      try {
          const saved = localStorage.getItem(storageKeys.VOCAB_KEY);
          return saved ? JSON.parse(saved) : [];
      } catch (err: any) {
          const msg = err?.message || 'Unknown error';
          console.error(`[App] LocalStorage initialization error for key "${storageKeys.VOCAB_KEY}":`, msg);
          initializationErrors.current.push({ key: storageKeys.VOCAB_KEY, error: msg });
          return [];
      }
  });
  const [inclusionRate, setInclusionRate] = useState<number>(() => {
      const saved = localStorage.getItem(storageKeys.INCLUSION_RATE_KEY);
      return saved ? Number(saved) : 50;
  });

  const [focusGrammar, setFocusGrammar] = useState<string[]>(() => {
    try {
        const saved = localStorage.getItem(storageKeys.GRAMMAR_KEY);
        return saved ? JSON.parse(saved) : [];
    } catch (err: any) {
        const msg = err?.message || 'Unknown error';
        console.error(`[App] LocalStorage initialization error for key "${storageKeys.GRAMMAR_KEY}":`, msg);
        initializationErrors.current.push({ key: storageKeys.GRAMMAR_KEY, error: msg });
        return [];
    }
  });
  const [grammarInclusionRate, setGrammarInclusionRate] = useState<number>(() => {
      const saved = localStorage.getItem(storageKeys.GRAMMAR_RATE_KEY);
      return saved ? Number(saved) : 50;
  });

  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [settingsModalTab, setSettingsModalTab] = useState<'General' | 'Vocabulary' | 'Grammar' | null>(null);
  const [presentingBlockId, setPresentingBlockId] = useState<number | null>(null);

  const stateRef = useRef({
      blocks, difficulty, tone, theme, focusVocabulary, inclusionRate, focusGrammar, grammarInclusionRate
  });

  useEffect(() => {
      stateRef.current = {
          blocks, difficulty, tone, theme, focusVocabulary, inclusionRate, focusGrammar, grammarInclusionRate
      };
  }, [blocks, difficulty, tone, theme, focusVocabulary, inclusionRate, focusGrammar, grammarInclusionRate]);

  useEffect(() => {
    if (logger && initializationErrors.current.length > 0) {
      initializationErrors.current.forEach(({ key, error }) => {
        logFocusItem('General UI', 'LocalStorage Corruption', 0, null, 1, [error], key);
      });
      initializationErrors.current = [];
    }
  }, [logFocusItem, logger]);

  useDebouncedSave(storageKeys.BLOCKS_KEY, blocks, 500);
  useDebouncedSave(storageKeys.PATHS_KEY, paths, 500);
  useDebouncedSave(storageKeys.DIFFICULTY_KEY, difficulty);
  useDebouncedSave(storageKeys.TONE_KEY, tone);
  useDebouncedSave(storageKeys.THEME_KEY, theme);
  useDebouncedSave(storageKeys.VOCAB_KEY, focusVocabulary);
  useDebouncedSave(storageKeys.INCLUSION_RATE_KEY, inclusionRate);
  useDebouncedSave(storageKeys.GRAMMAR_KEY, focusGrammar);
  useDebouncedSave(storageKeys.GRAMMAR_RATE_KEY, grammarInclusionRate);

  const totalTime = useMemo(() => {
      return blocks.reduce((sum, block) => sum + calculateExerciseDuration(block.exerciseType, block.height, block.quantity), 0);
  }, [blocks]);

  const enterPresentation = useCallback((blockId: number) => {
      setPresentingBlockId(blockId);
      setIsSidebarOpen(false);
      setSettingsModalTab(null);
  }, []);

  const exitPresentation = useCallback(() => setPresentingBlockId(null), []);

  const nextSlide = useCallback(() => {
      if (presentingBlockId === null) return;
      const currentIndex = blocks.findIndex(b => b.id === presentingBlockId);
      if (currentIndex !== -1 && currentIndex < blocks.length - 1) {
          setPresentingBlockId(blocks[currentIndex + 1].id);
      }
  }, [blocks, presentingBlockId]);

  const prevSlide = useCallback(() => {
      if (presentingBlockId === null) return;
      const currentIndex = blocks.findIndex(b => b.id === presentingBlockId);
      if (currentIndex > 0) {
          setPresentingBlockId(blocks[currentIndex - 1].id);
      }
  }, [blocks, presentingBlockId]);

  const handleExportState = useCallback(() => {
      const { blocks, difficulty, tone, theme, focusVocabulary, inclusionRate, focusGrammar, grammarInclusionRate } = stateRef.current;
      const data = {
          version: '2.1.0', timestamp: new Date().toISOString(),
          state: { blocks, paths, difficulty, tone, theme, focusVocabulary, inclusionRate, focusGrammar, grammarInclusionRate }
      };
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `practice-genie-project-${new Date().toISOString().split('T')[0]}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
  }, [paths]);

  const handleImportState = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = (event) => {
          try {
              const json = JSON.parse(event.target?.result as string);
              if (json.state) {
                  const { state } = json;
                  if (state.blocks) setBlocks(state.blocks);
                  if (state.paths) setPaths(state.paths);
                  if (state.difficulty) setDifficulty(state.difficulty);
                  if (state.tone) setTone(state.tone);
                  if (state.theme) setTheme(state.theme);
                  if (state.focusVocabulary) setFocusVocabulary(state.focusVocabulary);
                  if (state.inclusionRate) setInclusionRate(state.inclusionRate);
                  if (state.focusGrammar) setFocusGrammar(state.focusGrammar);
                  if (state.grammarInclusionRate) setGrammarInclusionRate(state.grammarInclusionRate);
              }
          } catch (error) {
              alert("Invalid project file.");
          }
      };
      reader.readAsText(file);
      e.target.value = '';
  }, []);

  const handleClearBoard = useCallback(() => {
      if (window.confirm("Are you sure you want to clear the entire whiteboard?")) {
          setBlocks([]);
          setPaths([]);
      }
  }, []);

  const addBlock = useCallback((type: ExerciseType, dropX?: number, dropY?: number) => {
    const { difficulty, tone, theme, focusVocabulary, inclusionRate, focusGrammar, grammarInclusionRate } = stateRef.current;
    setBlocks(prevBlocks => {
      const { width: newBlockWidth, height: newBlockHeight } = EXERCISE_SIZE_OVERRIDES[type] || DEFAULT_BLOCK_DIMENSIONS;
      let finalPos = (dropX !== undefined && dropY !== undefined) 
          ? { x: Math.max(0, dropX - newBlockWidth / 2), y: Math.max(0, dropY - newBlockHeight / 2) }
          : findFreePosition(prevBlocks, newBlockWidth, newBlockHeight);
      let maxZ = 0;
      for (const b of prevBlocks) { if ((b.zIndex || 0) > maxZ) maxZ = b.zIndex || 0; }
      const newBlock: ExerciseBlockState = {
        id: Date.now(), exerciseType: type, difficulty, tone, theme, focusVocabulary, inclusionRate, focusGrammar, grammarInclusionRate,
        x: finalPos.x, y: finalPos.y, width: newBlockWidth, height: newBlockHeight, zIndex: maxZ + 1, isGenerated: false,
      };
      return [...prevBlocks, newBlock];
    });
  }, []);

  const updateBlock = useCallback((blockId: number, updates: Partial<ExerciseBlockState>) => {
    setBlocks(prevBlocks => prevBlocks.map(block => block.id === blockId ? { ...block, ...updates } : block));
  }, []);

  const removeBlock = useCallback((blockId: number) => {
    setBlocks(prevBlocks => prevBlocks.filter(block => block.id !== blockId));
    if (presentingBlockId === blockId) exitPresentation();
  }, [presentingBlockId, exitPresentation]);

  const focusBlock = useCallback((blockId: number) => {
    setBlocks(prevBlocks => {
      let maxZ = 0;
      let maxZCount = 0;
      let blockIndex = -1;
      let currentZ = -1;

      for (let i = 0; i < prevBlocks.length; i++) {
          const b = prevBlocks[i];
          const z = b.zIndex || 0;

          if (z > maxZ) {
              maxZ = z;
              maxZCount = 1;
          } else if (z === maxZ) {
              maxZCount++;
          }

          if (b.id === blockId) {
              blockIndex = i;
              currentZ = z;
          }
      }

      if (blockIndex === -1 || (currentZ === maxZ && maxZCount === 1)) {
          return prevBlocks;
      }

      const newBlocks = [...prevBlocks];
      newBlocks[blockIndex] = { ...newBlocks[blockIndex], zIndex: maxZ + 1 };
      return newBlocks;
    });
  }, []);

  const cycleDifficulty = useCallback(() => {
    setDifficulty(prevDiff => {
        const currentIndex = DIFFICULTY_LEVELS.indexOf(prevDiff);
        const nextIndex = (currentIndex + 1) % DIFFICULTY_LEVELS.length;
        return DIFFICULTY_LEVELS[nextIndex] as Difficulty;
    });
  }, []);

  const handleOpenSettings = useCallback((tab: 'General' | 'Vocabulary' | 'Grammar') => setSettingsModalTab(tab), []);
  const handleToggleSidebar = useCallback(() => setIsSidebarOpen(prev => !prev), []);
  const handleCloseSettings = useCallback(() => setSettingsModalTab(null), []);
  const handleCloseSidebar = useCallback(() => setIsSidebarOpen(false), []);
  const handleAddPath = useCallback((path: DrawingPath) => setPaths(prev => [...prev, path]), []);
  const handleToggleDrawing = useCallback(() => setIsDrawingMode(prev => !prev), []);

  return (

    <div className="h-screen w-screen flex font-casual antialiased overflow-hidden bg-slate-800 text-slate-200">


      <RadialMenu 
          onOpenSettingsTab={handleOpenSettings}
          onExportState={handleExportState}
          difficulty={difficulty}
          onCycleDifficulty={cycleDifficulty}
          isDrawingMode={isDrawingMode}
          onToggleDrawing={handleToggleDrawing}
      />

      {settingsModalTab && (
          <GlobalSettings 
              difficulty={difficulty} setDifficulty={setDifficulty}
              tone={tone} setTone={setTone}
              theme={theme} setTheme={setTheme}
              focusVocabulary={focusVocabulary} setFocusVocabulary={setFocusVocabulary}
              inclusionRate={inclusionRate} setInclusionRate={setInclusionRate}
              focusGrammar={focusGrammar} setFocusGrammar={setFocusGrammar}
              grammarInclusionRate={grammarInclusionRate} setGrammarInclusionRate={setGrammarInclusionRate}
              totalTime={totalTime}
              onClose={handleCloseSettings}
              initialTab={settingsModalTab}
          />
      )}

      <Sidebar 
        isSidebarOpen={isSidebarOpen}
        onToggleSidebar={handleToggleSidebar}
        onAddExercise={addBlock}
        onExportState={handleExportState}
        onImportState={handleImportState}
        onClearBoard={handleClearBoard}
      />
      
      <div 
          onClick={handleCloseSidebar}
          className={`fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-30 transition-opacity duration-300 ease-in-out ${
            isSidebarOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'
          }`}
          aria-hidden="true"
      ></div>

      <div className="flex-grow flex flex-col relative">
        <Whiteboard 
          blocks={blocks}
          onAddBlock={addBlock}
          onUpdateBlock={updateBlock} 
          onRemoveBlock={removeBlock} 
          onFocusBlock={focusBlock}
          presentingBlockId={presentingBlockId}
          onEnterPresentation={enterPresentation}
          onExitPresentation={exitPresentation}
          onNextSlide={nextSlide}
          onPrevSlide={prevSlide}
          paths={paths}
          onAddPath={handleAddPath}
          isDrawingMode={isDrawingMode}
          disableInteraction={isSidebarOpen}
        />
      </div>
    </div>

  );
};

export default App;
